language: php
sudo: false

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    global:
        - TEST_SERVER=http://127.0.0.1:10000/server.php
        - SYMFONY_VERSION=2.3.*
        - GUZZLE_VERSION=6.*
        - COMPOSER_PREFER_LOWEST=false
        - ENABLE_CURL=true

install:
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then printf "\n" | pecl install propro; fi
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then printf "\n" | pecl install raphf; fi
    - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]] && [[ "$TRAVIS_PHP_VERSION" != "7" ]]; then printf "\n" | pecl install pecl_http; fi
    - if [[ "$ENABLE_CURL" = false ]]; then mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d; fi
    - if [[ "$ENABLE_CURL" = false ]]; then echo "disable_functions = curl_init" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    - if [[ "$TRAVIS_PHP_VERSION" = "5.6" ]]; then echo "always_populate_raw_post_data = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
    - php -S 127.0.0.1:10000 -t tests/Fixtures > /dev/null 2>&1 &
    - composer require symfony/event-dispatcher:${SYMFONY_VERSION} --no-update --dev
    - if [[ "$GUZZLE_VERSION" != "6.*" ]]; then composer require guzzlehttp/guzzle:${GUZZLE_VERSION} --no-update --dev; fi
    - if [[ "$SYMFONY_VERSION" = *dev* ]]; then sed -i "s/\"MIT\"/\"MIT\",\"minimum-stability\":\"dev\"/g" composer.json; fi
    - composer update --prefer-source `if [[ $COMPOSER_PREFER_LOWEST = true ]]; then echo "--prefer-lowest --prefer-stable"; fi`

script: bin/phpunit --configuration phpunit.travis.xml --coverage-clover clover.xml

after_script:
    - sed -i "/^disable_functions =.*$/d" ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - bin/coveralls -v

matrix:
    include:
        - php: 5.6
          env: GUZZLE_VERSION=4.*
        - php: 5.6
          env: GUZZLE_VERSION=5.*
        - php: 5.4
          env: COMPOSER_PREFER_LOWEST=true
        - php: 5.6
          env: ENABLE_CURL=false
        - php: 5.6
          env: SYMFONY_VERSION=2.1.*
        - php: 5.6
          env: SYMFONY_VERSION=2.2.*
        - php: 5.6
          env: SYMFONY_VERSION=2.4.*
        - php: 5.6
          env: SYMFONY_VERSION=2.5.*
        - php: 5.6
          env: SYMFONY_VERSION=2.6.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.*
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*@dev
    allow_failures:
        - php: 7.0
        - php: hhvm
        - env: SYMFONY_VERSION=2.8.*@dev

notifications:
    email: geloen.eric@gmail.com
